#Start Phase settings
player-settings:
  max: 8
  min: 2
start-counter: 5 #Seconds until game starts fully.

#Move Back
move-back-lobby: 'YourLobbyNameHere' #Please set up this. It is used for the spectator "leave" item.

#Permissions
command:
  start:
    usage: '%prefix% &7Use: &f/start &7| Force start the game (min. 2 players).'
    permission: 'skywarshg.forcestart'
  configure:
    usage: '%prefix% &7Use: &f/configure &7| Switch to configure mode.'
    permission: 'skywarshg.configure'