#Arenas
arenas:
  - world #You can add multiple worlds. The plugin will choose a random one. Write the name of the folder here!

#Start Phase settings
player-settings:
  max: 8
  min: 2
start-counter: 5 #Seconds until game starts fully.

#Move Back
move-back-lobby: 'YourLobbyNameHere' #Please set up this. It is used for the spectator "leave" item.

#Permissions
command-permission:
  start: 'skywarshg.forcestart'
  configure: 'skywarshg.configure'